# action.yml
name: 'Xamain Android container build action'
description: 'Build Xamarin Android projection inside a docker conainer'
inputs:
  SolutionPath:  # id of input
    description: 'Path to the solution file, relative to repository root'
    required: true
    default: ''
  ProjectPath:  # id of input
    description: 'Path to the Android project file, relative to repository root'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.SolutionPath }}
    - ${{ inputs.ProjectPath }}
